insert into MOVIE_DETAILS values(1,'Ramesh Sippy','Sholay','Sippy Films','15 August 1975');
insert into CAST_DETAILS values(111,16,'male','Amitabh Bacchan',1);
insert into CAST_DETAILS values(112,15,'male','Dharmendra',1);
insert into CAST_DETAILS values(113,5,'female','Hemamalini',1);
insert into CAST_DETAILS values(114,15,'male','Sanjeev Kumar',1);
insert into CAST_DETAILS values(115,24,'male','Amzad Khan',1);
insert into CAST_DETAILS values(116,12,'female','Jaya Bhaduri',1);
insert into MOVIE_DETAILS_CAST_LIST values(1,111);
insert into MOVIE_DETAILS_CAST_LIST values(1,112);
insert into MOVIE_DETAILS_CAST_LIST values(1,113);
insert into MOVIE_DETAILS_CAST_LIST values(1,114);
insert into MOVIE_DETAILS_CAST_LIST values(1,115);
insert into MOVIE_DETAILS_CAST_LIST values(1,116);
